Sagar.BookStore/Sagar.BookStore/Components/TopBooksViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Sagar.BookStore.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sagar.BookStore.Components
{
    public class TopBooksViewComponent:ViewComponent
    {
        private readonly IBookRepository _bookRepository;

        public TopBooksViewComponent(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var books = await _bookRepository.GetTopBooksAsync();
            return View(books);
        }
    }
}

Sagar.BookStore/Sagar.BookStore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sagar.BookStore.Controllers
{
    public class HomeController : Controller
    {
        [ViewData]
        public string Title { get; set; }
        public IActionResult Index()
        {
            Title = "Home";
            return View();
        
        }
        public IActionResult AboutUs()
        {
            Title = "About";
            return View();
        }
        public IActionResult ContactUs()
        {
            Title = "Contact";
            return View();
        }
    }
}

Sagar.BookStore/Sagar.BookStore/Views/Home/AboutUs.cshtml
@*@{
    ViewData["Title"] = "About";
}*@
<h2> I am about us page</h2>

<p>dfdkjhk</p>

Sagar.BookStore/Sagar.BookStore/Views/Home/ContactUs.cshtml
@*@{
    ViewData["Title"] = "Contact Us";
}*@
<h1>ContactUs</h1>

Sagar.BookStore/Sagar.BookStore/Views/Home/Index.cshtml
@*@{ 
    ViewData["Title"] = "Home";
}*@
<section class="jumbotron text-center">
    <div class="controller">
        <environment include="Development">
            <h3>Development</h3>
        </environment>
        <environment include="Production,Staging">
            <h3>Production</h3>
        </environment>
        <h1>Welcome to Book Store</h1>
        <p>
            aaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        </p>
        <p>
            <a href="#" class="btn btn-primary my-2">Search Books</a>
        </p>
    </div>
</section>

<div class="py-5 bg-light">
    <div class="container">
        <h3 class="h3">Top Books</h3>
        @*@await Component.InvokeAsync("TopBooks")*@ 
        <vc:top-books></vc:top-books>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
           // alert("documentis ready")
        });
    </script>
}